using global::AutoBogus;
using Net.Nowhereatall.Xfty.Core;
using Net.Nowhereatall.Xfty.Lookup;

namespace Net.Nowhereatall.Xfty.AutoBogus;

/// <summary>
/// Intercepts a request for a type with a registered <see cref="IRecordProvider"/>
/// and answers it with <c>new RecordProvider(type, lookup).SetInsertMode(insertMode).SetInclusivity(inclusivity).Supply()</c>
/// instead of AutoBogus's own generation - so <c>faker.Generate&lt;Contact&gt;()</c>
/// gets a fully-formed XFTY graph rather than AutoBogus's own recursive
/// auto-property population, which knows nothing about XFTY's relationships,
/// shared ancestors, or cycle guards. Anything requested that XFTY has no
/// Provider for is left alone (<see cref="CanOverride"/> returns false),
/// letting AutoBogus's own generation handle it as usual.
///
/// <see cref="Preinitialize"/> is false - AutoBogus does not construct or
/// populate an instance before calling <see cref="Generate"/>, so nothing
/// generated by AutoBogus's own engine is thrown away or overwritten by
/// what XFTY produces.
///
/// Register directly via AutoBogus's own configuration, or use
/// <see cref="XftyAutoBogus.CreateFaker"/> for the one-line form.
/// </summary>
public sealed class XftyAutoBogusOverride(IProviderLookup lookup, InsertMode insertMode, InsertInclusivity inclusivity) : AutoGeneratorOverride
{
    public override bool Preinitialize => false;

    public override bool CanOverride(AutoGenerateContext context) => this.IsRegistered(context.GenerateType);

    public override void Generate(AutoGenerateOverrideContext context) =>
        context.Instance = new RecordProvider(context.GenerateType, lookup).SetInsertMode(insertMode).SetInclusivity(inclusivity).Supply();

    private bool IsRegistered(Type type)
    {
        try
        {
            _ = lookup.Get(type);
            return true;
        }
        catch (LookupException)
        {
            return false;
        }
    }
}
