using global::AutoBogus;
using Net.NowhereAtAll.Xfty.Core;
using Net.NowhereAtAll.Xfty.Lookup;

namespace Net.NowhereAtAll.Xfty.AutoBogus;

/// <summary>
/// Intercepts a request for a type with a registered <see cref="IRecordProvider"/>
/// and answers it with <c>new RecordProvider(type, lookup).SetInsertMode(insertMode).SetInclusivity(inclusivity).Supply()</c>
/// instead of AutoBogus's own generation - so <c>faker.Generate&lt;Contact&gt;()</c>
/// gets a fully-formed XFTY graph rather than AutoBogus's own recursive
/// auto-property population, which knows nothing about XFTY's relationships,
/// shared ancestors, or cycle guards. Anything requested that XFTY has no
/// Provider for is left alone (<see cref="CanOverride"/> returns false),
/// letting AutoBogus's own generation handle it as usual.
///
/// <see cref="Preinitialize"/> is false - AutoBogus does not construct or
/// populate an instance before calling <see cref="Generate"/>, so nothing
/// generated by AutoBogus's own engine is thrown away or overwritten by
/// what XFTY produces.
///
/// AutoBogus's <see cref="Generate"/> is a synchronous SPI - not something
/// this package controls the shape of - so this bridges sync-over-async via
/// <c>Task.Run(...).GetAwaiter().GetResult()</c>. The inner <c>Task.Run(...)</c>
/// is deliberate, not decoration: it forces XFTY's generation onto a fresh
/// thread-pool thread with no captured synchronization context at all, so
/// the blocking wait below can never deadlock waiting on a continuation
/// that needed the very thread it's blocking - regardless of what thread
/// calls in (a UI thread, classic ASP.NET's request context, anything).
/// XFTY is itself a piece of test infrastructure - a third source of
/// failures beyond the code under test and the tests themselves - so this
/// intentionally trades a negligible thread-pool hop for eliminating a
/// whole class of hard-to-diagnose hangs, rather than only documenting the
/// risk away for the contexts already known to be safe.
///
/// Register directly via AutoBogus's own configuration, or use
/// <see cref="XftyAutoBogus.CreateFaker"/> for the one-line form.
/// </summary>
public sealed class XftyAutoBogusOverride(IProviderLookup lookup, InsertMode insertMode, InsertInclusivity inclusivity) : AutoGeneratorOverride
{
    public override bool Preinitialize => false;

    public override bool CanOverride(AutoGenerateContext context) => this.IsRegistered(context.GenerateType);

    public override void Generate(AutoGenerateOverrideContext context) =>
        context.Instance = Task.Run(() => new RecordProvider(context.GenerateType, lookup)
            .SetInsertMode(insertMode).SetInclusivity(inclusivity).Supply()).GetAwaiter().GetResult();

    private bool IsRegistered(Type type)
    {
        try
        {
            _ = lookup.Get(type);
            return true;
        }
        catch (LookupException)
        {
            return false;
        }
    }
}
